# Credits: Kiley W.
# https://github.com/DreamyKiley/UnlimitedBamboo

# Maximum bamboo height
# Vanilla: 16
max-height: 32

# How often to check for growth (in ticks)
# Vanilla: 4096, roughly 3.4 minutes, I do not reccomend lowering
growth-interval-ticks: 4096

# Chance for bamboo to grow on each check (0.0 - 1.0)
# Vanilla: 0.33 = roughly 1 in 3 chance per growth check
growth-chance: 0.33